name: Deploy Proxy to YC
on:
  push:
    branches: [ main ] # Убедись, что твоя ветка называется main, а не master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to YC Registry
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_KEY }}

      - name: Build and Push Docker Image
        run: |
          # Собираем образ и пушим в твой реестр
          docker build -t cr.yandex/crp05sipubrj79k08hta/proxy-bridge:latest .
          docker push cr.yandex/crp05sipubrj79k08hta/proxy-bridge:latest

      - name: Deploy Serverless Container
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          export PATH=$PATH:/home/runner/yandex-cloud/bin
          
          echo '${{ secrets.YC_SA_JSON_KEY }}' > sa_key.json
          yc config set service-account-key sa_key.json
          yc config set folder-id b1g08mvrjqt5o2fg6oso

          # Теперь имя совпадает с тем, что в Облаке
          yc serverless container revision deploy \
            --container-name vless-bridge \
            --image cr.yandex/crp05sipubrj79k08hta/proxy-bridge:latest \
            --cores 1 \
            --memory 256MB \
            --concurrency 50 \
            --execution-timeout 60s \
            --service-account-id ajedis5su2hi66198g4r
